version: "3.9"

services:
  php:
    container_name: php
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - db
    links:
      - db
    volumes:
      - type: bind
        source: ./
        target: /var/www/html
      - type: bind
        source: ./apache2.conf
        target: /etc/apache2/apache2.conf

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'filou'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'cesi'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'cesi'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '8001:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'

